### ISSUE TITLE
E-mail

### ISSUE THREAD

**Issue by thiagobitencourt** [thiagobitencourt/programa101#6]
Pessoal, por favor comentem com seu contato de e-mail. De preferencia gmail, pois vamos testar uma ferramenta google para usar em nossas aulas.

**Comment by DanielTambosetti** [comment]
danieel.tam@gmail.com

**Comment by cleitonbaumgardt** [comment]
cleitonbaumgardt98@gmail.com

**Comment by gabrielbertollo** [comment]
gabrielbertollo.gb@gmail.com

**Comment by WelyssonSantos** [comment]
welyssonsantos91@gmail.com

**Comment by alinealflen** [comment]
alflenaline@gmail.com

**Comment by velosoleo** [comment]
osolevleo@gmail.com

**Comment by mauriciobritovaz** [comment]
m.britovaz@gmail.com

**Comment by wilker1234** [comment]
wilker.augusto25@gmail.com

**Comment by EdilsonReich** [comment]
edilsonreich@gmail.com

**Comment by fernandouller** [comment]
fernandoullerdev@gmail.com

**Comment by matiasmendozadev** [comment]
matiasezequiel.qwerty@gmail.com

**Comment by Guxtavon** [comment]
wake.blitz@gmail.com

**Comment by adrianodonizete** [comment]
adriano.wds@gmail.com

**Comment by ChristianoGrabovski** [comment]
c.grabovski@gmail.com

**Comment by thiagobitencourt** [comment]
gui.guesser@gmail.com

**Comment by EdilsonZomer** [comment]
edilsonzoomer@gmail.com

**Comment by dekhy** [comment]
rodrigocantuario1@gmail.com

**Comment by lucas16710** [comment]
amauri77lucas@gmail.com

**Comment by djiovani-douglas** [comment]
djiovani.douglas@gmail.com

**Comment by clevertondecker** [comment]
decker.cleverton@gmail.com
